### ISSUE TITLE
Cannot test with storyshots due to findDomNode

### ISSUE THREAD

**Issue by justin808** [YouCanBookMe/react-datetime#275]
# Summary: We cannot use storyshots with react-datetime

We are using: https://github.com/storybooks/storyshots for testing.

Per this issue: 
https://github.com/facebook/react/issues/7371#issuecomment-260946944

and per this code:

https://github.com/YouCanBookMe/react-datetime/blob/5c617dcc7f23f667761b26fb4565d5f33d44dea7/src/onClickOutside.js#L58

```javascript
   }(React.findDOMNode(this), this.handleClickOutside));
```

This fails with this obscure error:

```
Storyshots › DateTimePicker › All defaults (input is true by default)

    Invariant Violation: getNodeFromInstance: Invalid argument.

      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:162:77)
      at Object.findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at componentDidMount (node_modules/react-datetime/src/onClickOutside.js:58:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (node_modules/storyshots/dist/index.js:113:56)
```

**Comment by jiayuan6311** [comment]
+1, we met the same issue

**Comment by simeg** [comment]
@justin808 @jiayuan6311 Are you using the latest version? I know the dependency for handling that got replaced, maybe it will resolve your problem. 

The code that is causing the problem lives in a differente repo: https://github.com/Pomax/react-onclickoutside

**Comment by jiayuan6311** [comment]
We are on the latest version but the problem still persists. The problem is with `ReactDOM.findDOMNode`. It is still in the latest `react-onclickoutside`([Link](https://github.com/Pomax/react-onclickoutside/blob/5b023e90b09ea148285296c31041e35d7aa5b8dd/index.js#L153)).
Is there any way to work around this?

**Comment by simeg** [comment]
@jiayuan6311 As `react-onclickoutside` is a library this component depends on, I don't see any way around this unfortunately :/

**Comment by layneanderson** [comment]
@justin808 , @jiayuan6311   Would a solution similar to what @simeg found for #384 work in this situation too?

**Comment by simeg** [comment]
Closing due to inactivity.
